on:
  pull_request:
    types: [opened]
jobs:
  list-change-stack:
    runs-on: ubuntu-latest
    name: list cfn stack change set
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: describe change set
        id: describe-change-set
        uses: Blue-Pix/describe-cfn-change-set@v2.1
        with:
          stack_name: cfn-validate-basic
          template_body: basic_after.cf.yml
      - name: echo output
        run: echo "Result was ${{ steps.describe-change-set.outputs.result }}"
