on:
  pull_request:
    types: [opened]
jobs:
  list-change-stack:
    runs-on: ubuntu-latest
    name: list cfn stack change set
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: describe change set
        id: describe-change-set
        uses: Blue-Pix/describe-cfn-change-set@v2.1
        with:
          stack_name: cfn-validate-basiccccccccc
          template_body: basic_after.cf.yml
      - name: echo output
        run: echo "Result was ${{ steps.describe-change-set.outputs.result }}"
      - name: archive change set
        uses: actions/upload-artifact@v1
        with:
          name: change-set-archive
          path: ${{ steps.describe-change-set.outputs.file_path }}
